theme: minima
title: [O título do seu site]
description: [Uma breve descrição do seu site]
email: [Seu endereço de e-mail]
instagram_username: [Seu nome de usuário no Twitter] # caso possua um
github_username:  [Seu nome de usuário no GitHub] # caso deseje incluir
